version: '3'

networks:
    laravel:
        driver: bridge

volumes:
    pmsearch-uploads:
    pmsearch-db:

services:
    frontend:
      env_file: ./.env.docker
      build:
        context: .
        dockerfile: nginx.dockerfile
        args:
          - UID=${UID:-1000}
          - GID=${GID:-1000}
      image: sgscoaisearchfrontend.azurecr.io/pm-search-ui-nginx

    backend:
      env_file: ./.env.docker

    worker:
      env_file: ./.env.docker

    redis:
      image: redis:alpine
      restart: unless-stopped
      ports:
        - "6379:6379"
      networks:
        - laravel
      healthcheck:
        test:
          - CMD
          - redis-cli
          - ping
        retries: 3
        timeout: 5s


