version: '3'

networks:
    laravel:
        driver: bridge

volumes:
    pmsearch-uploads:
    pmsearch-db:

services:
    web:
        build:
            context: .
            dockerfile: dockerfiles/nginx.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        env_file: ./.env.azure
        image: sgscoaisearchfrontend.azurecr.io/pm-search-ui-web
        ports:
            - "80:80"
        depends_on:
            - php
            - redis
            - queue
        networks:
            - laravel
        volumes:
            - pmsearch-uploads:/var/www/html/storage/app
        expose:
            - 80

    php:
        build:
            context: .
            dockerfile: dockerfiles/php.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        env_file: ./.env.azure
        image: sgscoaisearchfrontend.azurecr.io/pm-search-ui-php
        ports:
            - "9000:9000"
        networks:
            - laravel
        volumes:
            - pmsearch-uploads:/var/www/html/storage/app
            - pmsearch-db:/var/www/html/database/mounted
        environment:
            APP_ENV: local
            CONTAINER_ROLE: app

    queue:
        build:
            context: .
            dockerfile: dockerfiles/php.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        env_file: ./.env.azure
        image: sgscoaisearchfrontend.azurecr.io/pm-search-ui-queue
        command: [ 'php', '/var/www/html/artisan', "queue:work", "--verbose", "--tries=3", "--timeout=90" ]
        networks:
            - laravel
        volumes:
            - pmsearch-uploads:/var/www/html/storage/app
            - pmsearch-db:/var/www/html/database/mounted
        environment:
            APP_ENV: local
            CONTAINER_ROLE: worker


    redis:
        image: redis:alpine
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - laravel
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s


