version: '3'

networks:
    laravel:
        driver: bridge

volumes:
    pmsearch-uploads:
    pmsearch-db:

services:
    web:
        build:
            context: .
            dockerfile: dockerfiles/caddy.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        image: sgscoaisearchfrontend.azurecr.io/pm-search-ui-web
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - php
            - worker
        networks:
            - laravel
        volumes:
            - pmsearch-uploads:/var/www/html/storage/app/public
        expose:
            - 80
            - 443

    php:
        build:
            context: .
            dockerfile: dockerfiles/php.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        image: sgscoaisearchfrontend.azurecr.io/pm-search-ui-php
        ports:
            - "9000:9000"
        networks:
            - laravel
        volumes:
            - pmsearch-uploads:/var/www/html/storage/app/public
            - pmsearch-db:/var/www/html/database/mounted
        environment:
            APP_ENV: local
            CONTAINER_ROLE: app
            NOVA_USERNAME: ${NOVA_USERNAME}
            NOVA_LICENSE_KEY: ${NOVA_LICENSE_KEY}

    worker:
        build:
            context: .
            dockerfile: dockerfiles/php.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        image: sgscoaisearchfrontend.azurecr.io/pm-search-ui-queue
        command: [ 'php', '/var/www/html/artisan', "horizon"]
        networks:
            - laravel
        volumes:
            - pmsearch-uploads:/var/www/html/storage/app/public
            - pmsearch-db:/var/www/html/database/mounted
        environment:
            APP_ENV: local
            CONTAINER_ROLE: worker
            NOVA_USERNAME: ${NOVA_USERNAME}
            NOVA_LICENSE_KEY: ${NOVA_LICENSE_KEY}
        healthcheck:
            test:
                - CMD
                - php
                - artisan
                - horizon:status
            retries: 3
            timeout: 10s


