version: '3'

volumes:
    pmsearch-uploads:
        driver: azure_file
        driver_opts:
            share_name: pmsearchuiuploads
            storage_account_name: pmsearchuistorage
    pmsearch-db:
        driver: azure_file
        driver_opts:
            share_name: pmsearchuitestvolume
            storage_account_name: pmsearchuistorage

services:
    web:
        domainname: sgscopmsearchv2
        deploy:
            resources:
                reservations:
                    cpus: '0.5'
                    memory: '0.5G'
                limits:
                    cpus: '1'
                    memory: 1G

    php:
        deploy:
            resources:
                reservations:
                    cpus: '1'
                    memory: 1G
                limits:
                    cpus: '2'
                    memory: 2G

    queue:
        deploy:
            resources:
                reservations:
                    cpus: '0.5'
                    memory: 1G
                limits:
                    cpus: '2'
                    memory: 2G


