<?php

return [
    'image_search_url' => env('PM_SEARCH_IMAGE_ENDPOINT'),
    'text_search_url' => env('PM_SEARCH_TEXT_ENDPOINT'),


    'image_search_techs' => [
        'barcodesearch' => ['title' => 'Barcode', 'value' => false, 'position' => 1],
        'visualsearch' => ['title' => 'Visual', 'value' => true, 'position' => 2],
        //'docsearch' => ['title' => 'Document', 'value' => false, 'position' => 3],
        //'entitysearch' => ['title' => 'Entity', 'value' => false, 'position' => 4],
    ],

    'bridge_view_fields' => [
        'color_name', 'book', 'color_type', 'hex_colors',
        'font_name', 'layer_name',
        //'description',
    ],

    'fields-v1' => [
        'tag' => ['search' => true, 'display' => false, 'type' => 'list'],
        'Brand' => ['search' => true, 'display' => true, 'type' => 'list'],
        'JobId' => ['search' => false, 'display' => true, 'type' => 'list'],
        'score' => ['search' => false, 'display' => true, 'type' => 'list'],
        'SiteId' => ['search' => true, 'display' => true, 'type' => 'list'],
        'Variety' => ['search' => true, 'display' => true, 'type' => 'list'],
        'dieline' => ['search' => false, 'display' => true, 'type' => 'list'],
        'ocrtext' => ['search' => false, 'display' => false, 'type' => 'list'],
        'SiteName' => ['search' => false, 'display' => true, 'type' => 'list'],
        'IsGPNSite' => ['search' => false, 'display' => true, 'type' => 'list'],
        'JobStatus' => ['search' => true, 'display' => true, 'type' => 'list'],
        'Promotion' => ['search' => true, 'display' => true, 'type' => 'list'],
        'Substrate' => ['search' => true, 'display' => true, 'type' => 'list'],
        'file_name' => ['search' => false, 'display' => false, 'type' => 'list'],
        'PackTypeId' => ['search' => true, 'display' => true, 'type' => 'list'],
        'BarcodeType' => ['search' => true, 'display' => true, 'type' => 'list'],
        'ContactType' => ['search' => true, 'display' => true, 'type' => 'list'],
        'OrderTypeId' => ['search' => true, 'display' => true, 'type' => 'list'],
        'ProcessType' => ['search' => true, 'display' => true, 'type' => 'list'],
        'CustomerName' => ['search' => true, 'display' => true, 'type' => 'list'],
        'CustomerType' => ['search' => true, 'display' => true, 'type' => 'list'],
        'JobVersionId' => ['search' => false, 'display' => false, 'type' => 'list'],
        'LegalAddress' => ['search' => false, 'display' => true, 'type' => 'list'],
        'BarcodeNumber' => ['search' => false, 'display' => true, 'type' => 'list'],
        'BookedDateTime' => ['search' => true, 'display' => true, 'type' => 'date'],
        'NumberOfColors' => ['search' => false, 'display' => true, 'type' => 'list'],
        'AccountManagerId' => ['search' => false, 'display' => false, 'type' => 'list'],
        'CompanyLegalName' => ['search' => true, 'display' => true, 'type' => 'list'],
        'PortfolioGroupId' => ['search' => false, 'display' => false, 'type' => 'list'],
        'JobRelationshipId' => ['search' => true, 'display' => true, 'type' => 'list'],
        'NumberOfNewColors' => ['search' => false, 'display' => true, 'type' => 'list'],
        'SimplifiedGroupId' => ['search' => false, 'display' => false, 'type' => 'list'],
        'AccountManagerType' => ['search' => true, 'display' => true, 'type' => 'list'],
        'FormattedJobNumber' => ['search' => false, 'display' => true, 'type' => 'list'],
        'PortfolioGroupName' => ['search' => true, 'display' => true, 'type' => 'list'],
        'JobAccountManagerId' => ['search' => false, 'display' => false, 'type' => 'list'],
        'SimplifiedGroupName' => ['search' => true, 'display' => true, 'type' => 'list'],
    ],


    'fields' => [
        'formatted_job_number' => ['search' => false, 'display' => true, 'type' => 'list', 'response_type' => 'str', 'position'=> 1],
        'job_version_id' => ['search' => false, 'display' => false, 'type' => 'list', 'response_type' => 'str', 'position'=> 100],
        //'job_id' => ['search' => false, 'display' => false, 'type' => 'list', 'response_type' => 'str', 'position'=> 100],
        //'job_status' => ['search' => true, 'display' => true, 'type' => 'list', 'response_type' => 'str', 'position'=> 100],
        //'job_relationship_id' => ['search' => false, 'display' => false, 'type' => 'list', 'response_type' => 'str', 'position'=> 100],
        'job_relationship' => ['search' => true, 'display' => true, 'type' => 'list', 'response_type' => 'str', 'position'=> 100],
        //'site_id' => ['search' => false, 'display' => true, 'type' => 'list', 'response_type' => 'str', 'position'=> 100],
        'range_name' => ['search' => true, 'display' => true, 'type' => 'list', 'response_type' => 'str', 'position'=> 9],
        //'portfolio_group_id' => ['search' => false, 'display' => false, 'type' => 'list', 'response_type' => 'str', 'position'=> 100],
        'portfolio_group_name' => ['search' => true, 'display' => true, 'type' => 'list', 'response_type' => 'str', 'position'=> 8],
        //'simplified_group_id' => ['search' => false, 'display' => false, 'type' => 'list', 'response_type' => 'str', 'position'=> 100],
        'simplified_group_name' => ['search' => true, 'display' => true, 'type' => 'list', 'response_type' => 'str', 'position'=> 7],
        //'job_account_manager_id' => ['search' => false, 'display' => false, 'type' => 'list', 'response_type' => 'str', 'position'=> 100],
        //'account_manager_id' => ['search' => false, 'display' => false, 'type' => 'list', 'response_type' => 'str', 'position'=> 100],
        //'account_manager_type' => ['search' => true, 'display' => true, 'type' => 'list', 'response_type' => 'str', 'position'=> 100],
        'barcode_number' => ['search' => true, 'display' => true, 'type' => 'list', 'response_type' => 'str', 'position'=> 6],
        'barcode_type' => ['search' => true, 'display' => true, 'type' => 'list', 'response_type' => 'str', 'position'=> 5],
        'print_process' => ['search' => true, 'display' => true, 'type' => 'list', 'response_type' => 'str', 'position'=> 4],
        'substrate' => ['search' => true, 'display' => true, 'type' => 'list', 'response_type' => 'str', 'position'=> 3],
        'customer_design_ref' => ['search' => true, 'display' => true, 'type' => 'list', 'response_type' => 'str', 'position'=> 100],
        'printer_spec_url' => ['search' => false, 'display' => true, 'type' => 'list', 'response_type' => 'str', 'position'=> 100],
        'package_type' => ['search' => true, 'display' => true, 'type' => 'list', 'response_type' => 'str', 'position'=> 2],
        'order_type' => ['search' => true, 'display' => true, 'type' => 'list', 'response_type' => 'str', 'position'=> 100],
        'weight' => ['search' => true, 'display' => true, 'type' => 'list', 'response_type' => 'str', 'position'=> 10],
        'brand' => ['search' => true, 'display' => true, 'type' => 'list', 'response_type' => 'str', 'position'=> 11],
        'variety' => ['search' => true, 'display' => true, 'type' => 'list', 'response_type' => 'str', 'position'=> 12],
        'promotion' => ['search' => true, 'display' => true, 'type' => 'list', 'response_type' => 'str', 'position'=> 13],
        'packaging_reference' => ['search' => true, 'display' => true, 'type' => 'list', 'response_type' => 'str', 'position'=> 100],
        'pcm_type_profile_name' => ['search' => true, 'display' => true, 'type' => 'list', 'response_type' => 'str', 'position'=> 100],
        'pcm_type_desc' => ['search' => true, 'display' => true, 'type' => 'list', 'response_type' => 'str', 'position'=> 100],
        //'project_id' => ['search' => true, 'display' => true, 'type' => 'list', 'response_type' => 'str', 'position'=> 100],
        'project_name' => ['search' => true, 'display' => true, 'type' => 'list', 'response_type' => 'str', 'position'=> 100],
        'file_location' => ['search' => false, 'display' => true, 'type' => 'list', 'response_type' => 'str', 'position'=> 100],
        'account_manager_name' => ['search' => true, 'display' => true, 'type' => 'list', 'response_type' => 'str', 'position'=> 100],
        'site_name' => ['search' => true, 'display' => true, 'type' => 'list', 'response_type' => 'str', 'position'=> 3],
        'description' => ['search' => false, 'display' => true, 'type' => 'list', 'response_type' => 'str', 'position'=> 2],
        'url' => ['search' => false, 'display' => true, 'type' => 'list', 'response_type' => 'str', 'position'=> 100],
        'color_name' => ['search' => true, 'display' => true, 'type' => 'list', 'response_type' => 'list', 'position'=> 100],
        'book' => ['search' => true, 'display' => true, 'type' => 'list', 'response_type' => 'list', 'position'=> 100],
        'color_type' => ['search' => true, 'display' => true, 'type' => 'list', 'response_type' => 'list', 'position'=> 100],
        'hex_colors' => ['search' => true, 'display' => true, 'type' => 'list', 'response_type' => 'list', 'position'=> 100],
        'font_name' => ['search' => true, 'display' => true, 'type' => 'list', 'response_type' => 'list', 'position'=> 100],
        'layer_name' => ['search' => true, 'display' => true, 'type' => 'list', 'response_type' => 'list', 'position'=> 100],
        'contact_type' => ['search' => true, 'display' => true, 'type' => 'list', 'response_type' => 'list', 'position'=> 100],
        'customer_name' => ['search' => true, 'display' => true, 'type' => 'list', 'response_type' => 'list', 'position'=> 2],
        'customer_type' => ['search' => true, 'display' => true, 'type' => 'list', 'response_type' => 'list', 'position'=> 100],
        'number_of_colors' => ['search' => true, 'display' => true, 'type' => 'list', 'response_type' => 'int', 'position'=> 100],
        //'number_of_new_colors' => ['search' => true, 'display' => true, 'type' => 'list', 'response_type' => 'int', 'position'=> 100],
        'booked_date' => ['search' => true, 'display' => true, 'type' => 'date', 'response_type' => 'date', 'position'=> 10],
        //'file_date' => ['search' => false, 'display' => true, 'type' => 'list', 'response_type' => 'date', 'position'=> 100],
        'file_name' => ['search' => false, 'display' => true, 'type' => 'list', 'response_type' => 'str', 'position'=> 100],
        //'ocrtext' => ['search' => true, 'display' => true, 'type' => 'list', 'response_type' => 'str', 'position'=> 100],
        'dieline' => ['search' => true, 'display' => true, 'type' => 'list', 'response_type' => 'str', 'position'=> 100],
        'score' => ['search' => false, 'display' => true, 'type' => 'list', 'response_type' => 'float', 'position'=> 100],
        'tag' => ['search' => false, 'display' => false, 'type' => 'list', 'response_type' => 'str', 'position'=> 100],
        'language_count' => ['search' => false, 'display' => true, 'type' => 'list', 'response_type' => 'str', 'position'=> 100],
        'languages' => ['search' => false, 'display' => true, 'type' => 'list', 'response_type' => 'str', 'position'=> 2],
    ],

    'color_name_mappings' => [
        'pms1000c' => 'PANTONE Solid Coated',
        'pms1000u' => 'PANTONE Solid Uncoated',
        'pms1000m' => 'PANTONE Colors Matte',
        'pegc' => 'PANTONE+ Extended Gamut Coated',
        'ppasu' => 'PANTONE Pastels & Neons Uncoated',
        'ppasc' => 'PANTONE Pastels & Neons Coated',
        'pmetc' => 'PANTONE Premium Metallics Coated',
        'goeu' => 'PANTONE GoeGuide Uncoated',
        'goec' => 'PANTONE GoeGuide Coated',
    ]
];
